            - name: TruffleHog OSS
  # You may pin to the exact commit or the version.
  # uses: trufflesecurity/trufflehog@52d0ee5f5419ca938d3b7e358fe6f32131565026
  uses: trufflesecurity/trufflehog@v3.89.1
  with:
    # Repository path
    path: # optional, default is ./
    # Start scanning from here (usually main branch).
    base: # optional, default is 
    # Scan commits until here (usually dev branch).
    head: # optional
    # Extra args to be passed to the trufflehog cli.
    extra_args: # optional, default is 
    # Scan with this trufflehog cli version.
    version: # optional, default is latest
          
